using System;
using System.Threading.Tasks;
using DoganSystem.Constants;
using DoganSystem.Core.Domain.Entities;
using Microsoft.Extensions.Logging;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Volo.Abp.Emailing;
using Volo.Abp.Guids;

namespace DoganSystem.Application.Public;

public class PublicPageAppService : ApplicationService, IPublicPageAppService
{
    private readonly IEmailSender _emailSender;
    private readonly IRepository<ContactSubmission, Guid> _contactRepository;
    private readonly IGuidGenerator _guidGenerator;

    public PublicPageAppService(
        IEmailSender emailSender,
        IRepository<ContactSubmission, Guid> contactRepository,
        IGuidGenerator guidGenerator)
    {
        _emailSender = emailSender;
        _contactRepository = contactRepository;
        _guidGenerator = guidGenerator;
    }

    public Task<PublicPageInfoDto> GetHomePageInfoAsync()
    {
        return Task.FromResult(new PublicPageInfoDto
        {
            CompanyName = BrandMessages.CompanyName,
            CompanyDescription = BrandMessages.CompanyDescriptionArabic,
            Headline = BrandMessages.HeadlinePrimary,
            Tagline = BrandMessages.TaglinePrimary,
            PositioningStatement = BrandMessages.PositioningStatement
        });
    }

    public async Task SubmitContactFormAsync(ContactFormDto input)
    {
        // 1. Create and save contact submission using ABP Repository
        var submission = new ContactSubmission(
            id: _guidGenerator.Create(),
            name: input.Name,
            email: input.Email,
            message: input.Message,
            company: input.Company,
            serviceInterest: input.ServiceInterest
        );

        await _contactRepository.InsertAsync(submission, autoSave: true);

        Logger.LogInformation(
            "Contact form saved: Id={Id}, Name={Name}, Email={Email}, ServiceInterest={ServiceInterest}",
            submission.Id, input.Name, input.Email, input.ServiceInterest);

        // 2. Send email notification using ABP Email Service
        try
        {
            var emailBody = BuildContactNotificationEmail(input, submission.Id);

            await _emailSender.SendAsync(
                to: "info@doganconsult.com",
                subject: $"[DOGAN CONSULT] New Contact: {input.Name}",
                body: emailBody,
                isBodyHtml: true
            );

            Logger.LogInformation("Contact notification email sent for submission {Id}", submission.Id);
        }
        catch (Exception ex)
        {
            // Log but don't fail - the submission was saved successfully
            Logger.LogWarning(ex, "Failed to send contact notification email for submission {Id}", submission.Id);
        }
    }

    private static string BuildContactNotificationEmail(ContactFormDto input, Guid submissionId)
    {
        var serviceLabel = input.ServiceInterest switch
        {
            "telecom" => "Telecommunications Engineering",
            "datacenter" => "Data Center Design",
            "cybersecurity" => "Cybersecurity Consulting",
            "governance" => "ICT Program Governance",
            "other" => "Other",
            _ => "Not specified"
        };

        return $@"
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
        .header {{ background: #003366; color: white; padding: 20px; }}
        .content {{ padding: 20px; }}
        .field {{ margin-bottom: 15px; }}
        .label {{ font-weight: bold; color: #003366; }}
        .message {{ background: #f5f5f5; padding: 15px; border-radius: 5px; }}
        .footer {{ background: #f0f0f0; padding: 10px; font-size: 12px; color: #666; }}
    </style>
</head>
<body>
    <div class='header'>
        <h2>New Contact Form Submission</h2>
    </div>
    <div class='content'>
        <div class='field'>
            <span class='label'>Submission ID:</span> {submissionId}
        </div>
        <div class='field'>
            <span class='label'>Name:</span> {input.Name}
        </div>
        <div class='field'>
            <span class='label'>Email:</span> <a href='mailto:{input.Email}'>{input.Email}</a>
        </div>
        <div class='field'>
            <span class='label'>Company:</span> {input.Company ?? "Not provided"}
        </div>
        <div class='field'>
            <span class='label'>Service Interest:</span> {serviceLabel}
        </div>
        <div class='field'>
            <span class='label'>Message:</span>
            <div class='message'>{input.Message}</div>
        </div>
    </div>
    <div class='footer'>
        This email was automatically generated by DOGAN CONSULT website contact form.
    </div>
</body>
</html>";
    }
}
